TAO-634 : FEEDBACK : Voeg additionele RDW velden aan passage model
Amsterdam/iotsignals pull request #78
Opened 2021-10-04 13:21 UTC by moagstar

In deze PR worden additionele RDW velden aan het passage model toegevoegd. Om deze nieuwe velden te ondersteunen wordt er een tweede versie van de API beschikbaar gesteld. Het idee is dat we een beide versies van de berichten kunnen ondersteunen in 1 model. De nieuwe velden krijgen dus `NULL` waarden voor de bestaande rijen (of eventueel nieuwe rijen vanuit de "oude" versie van de API).

Deze opstelling maakt het mogelijk om een switch van v0 naar v1 te ondersteunen, maar we zouden ook ervoor kunnen kiezen om in een test fase v1 van de API naar een aparte tabel te laten schrijven op acceptatie.

Let op, de versie nummers zijn wel een beetje verwarrend. De versie nummers van de API zijn 0 en 1, terwijl de versie nummers van de payload zijn "passages-1" en "passages-2". Ik twijfel of ik dit recht moet trekken, dus graag je mening geven hierover.

2021-10-04 14:28 UTC, moagstar commented on api/src/iotsignals/__init__.py
> +    'v1': (1, 1, 0),
Ik weet niet of deze versie ooit in gebruik was, misschien beter om hier (1, 2, 0) van te maken? Of zelfs (2, 0, 0)?

2021-10-04 14:28 UTC, moagstar commented on api/src/iotsignals/routers.py
> +    """Signalen API versie 1 (in development)."""
Zou versie 0 moeten zijn

2021-10-07 11:27 UTC, jklardie commented
Algemene review, los van het technische: we kunnen deze change niet doorvoeren. De inbreuk op de privacy van weggebruikers is te groot. 

Met deze wijziging wordt het mogelijk om:

1. Een individuele passage te herleiden naar een persoon, (middels kentekenhash kan direct een link gelegd worden. Daarnaast voegen we velden toe; vervaldatum_apk en overige specificaties welke we kunnen combineren tot uniek herleidbare eigenschappen. Al met al verlagen we de data entropie aanzienlijk, waardoor de mate van zekerheid of een waarneming bij een specifiek persoon hoort sterk toeneemt). 
2. Een persoon op te zoeken in het passagearchief,
3. Van een persoon al zijn bewegingen langs de ANPR camera's te volgen. 

Dit is een extreme verandering en grote inbreuk op de privacy van onze inwoners. Tevens gaat het in tegen de initiële gedachte van het waarnemingenarchief. 

cc @snelis @kramer65; lijkt me goed als jullie hier ook concreet iets over zeggen.

2022-02-01 13:36 UTC, jklardie commented on api/src/passage/models.py
> +    milieuklasse_eg_goedkeuring_zwaar = models.CharField(max_length=255, null=True)
Besproken met privacy officers, DPIA up to date, aanpassingen volgen.

2022-02-10 09:54 UTC, jklardie commented
> Algemene review, los van het technische: we kunnen deze change niet doorvoeren. De inbreuk op de privacy van weggebruikers is te groot.
> 
> Met deze wijziging wordt het mogelijk om:
> 
>     1. Een individuele passage te herleiden naar een persoon, (middels kentekenhash kan direct een link gelegd worden. Daarnaast voegen we velden toe; vervaldatum_apk en overige specificaties welke we kunnen combineren tot uniek herleidbare eigenschappen. Al met al verlagen we de data entropie aanzienlijk, waardoor de mate van zekerheid of een waarneming bij een specifiek persoon hoort sterk toeneemt).
> 
>     2. Een persoon op te zoeken in het passagearchief,
> 
>     3. Van een persoon al zijn bewegingen langs de ANPR camera's te volgen.
> 
> 
> Dit is een extreme verandering en grote inbreuk op de privacy van onze inwoners. Tevens gaat het in tegen de initiële gedachte van het waarnemingenarchief.
> 
> cc @snelis @kramer65; lijkt me goed als jullie hier ook concreet iets over zeggen.

Hier is inmiddels lang en breed over gesproken. Er zijn dataminimalisaties uitgevoerd en de DPIA is up to date. De privacy officers zijn akkoord en de genoemde punten zijn opgelost.

2022-03-09 10:35 UTC, jklardie requested changes
minimal changes

2022-03-09 10:35 UTC, jklardie commented on Jenkinsfile
> +            sh "make --directory=api/ clean"
Clean up

2022-03-09 10:35 UTC, jklardie commented on Jenkinsfile
> -            sh "api/deploy/test/test.sh"
test.sh can be removed

2022-03-09 10:35 UTC, jklardie commented on api/src/passage/conversion.py
> +def downgrade(passage):
rename `convert_to_v1`

2022-03-10 09:08 UTC, merged